import Head from 'next/head'
import Navbar from 'components/Navbar'

import style from 'styles/Home.module.css'
import ContactButtons from 'components/ContactButtons'

export default function Home () {
  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <section className={style.hero}>
        <div className={style.heroText}>
          <h3>¡Hola a todos!</h3>
          <h2>Soy William</h2>
          <p>Un frontend developer que le encanta implementar diseños que inspiran y atraen a las personas</p>
          <ContactButtons />
        </div>
        <div className={style.heroImg}>
          <img src='/person@photo.png' alt='persona sonriente' />
        </div>
      </section>
    </div>
  )
}
